# Generated by Django 3.2.12 on 2022-04-07 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.CharField(max_length=10, unique=True)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('rate', models.CharField(max_length=4)),
                ('experience_req', models.CharField(max_length=2)),
                ('job_requirement', models.TextField(blank=True, max_length=500, verbose_name='describe the job requirement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usersext')),
            ],
        ),
        migrations.CreateModel(
            name='babysitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_number', models.CharField(max_length=40)),
                ('experience', models.CharField(max_length=2)),
                ('rating_score', models.CharField(max_length=4)),
                ('reviews', models.CharField(max_length=4)),
                ('rate', models.CharField(max_length=4)),
                ('available_startdate', models.DateField()),
                ('available_enddate', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usersext')),
            ],
        ),
    ]
