# Generated by Django 3.2.12 on 2022-04-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_babysitter_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='id',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
